# Generated by Django 3.2 on 2022-09-13 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='quiz_number',
        ),
    ]
