# Generated by Django 3.2 on 2022-09-13 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_quizz_quiz_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizzcfp4',
            old_name='TTTcfp',
            new_name='Testcfp4',
        ),
        migrations.RenameField(
            model_name='testcfp4',
            old_name='TTTcfp_id',
            new_name='Testcfp4_id',
        ),
    ]
