# Generated by Django 3.2 on 2022-09-13 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20220913_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcfp4',
            old_name='Testcfp4_id',
            new_name='Test_id',
        ),
    ]
