# Generated by Django 3.2 on 2022-09-13 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_rename_testcfp4_id_testcfp4_test_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizzcfp4',
            old_name='Testcfp4',
            new_name='Test',
        ),
        migrations.RenameField(
            model_name='testcfp4',
            old_name='Test_id',
            new_name='Testcfp4_id',
        ),
    ]
