# Generated by Django 3.2 on 2022-09-13 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20220913_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizzcfp4',
            old_name='Test',
            new_name='Testcfp4',
        ),
    ]
