# Generated by Django 3.2 on 2022-09-13 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_rename_test_quizzcfp4_testcfp4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzcfp4',
            name='Testcfp4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.testcfp4'),
        ),
    ]
