# Generated by Django 3.2 on 2022-09-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_quizzcfp4_testcfp4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='Test_id',
            new_name='Tests_id',
        ),
    ]
